export const houseplantsList = [
  'Money Tree Fertilizer',
  'Jade Fertilizer',
  'Christmas Cactus Fertilizer',
  'Cactus Fertilizer',
  'Succulent Plant Food',
  'Bonsai Fertilizer',
  'Air Plant Fertilizer',
  'Snake Plant Fertilizer',
  'House Plant Food',
  'Mycorrhizal Fungi for Houseplants',
  'Granular Houseplant Food',
  'Granular Monstera Fertilizer',
  'Granular Lemon Tree Fertilizer',
  'Granular Indoor Plant Food',
  'Granular Fig Tree Fertilizer',
  'Granular Bonsai Fertilizer',
  'Houseplant Root Supplement',
  'Succulent Root Supplement',
  'Fig Root Supplement',
  'Orchid Root Supplement',
  'Indoor Plant Food',
  'Instant Plant Food',
  'Ficus Fertilizer',
  'Banana Tree Fertilizer',
  'Philodendron Fertilizer',
  'Fern Fertilizer',
  'Dracaena Fertilizer',
  'Bird of Paradise Fertilizer',
  'Aloe Vera Fertilizer',
  'ZZ Plant Fertilizer',
  'Tropical Plant Fertilizer',
  'Pothos Fertilizer',
  'Bromeliad Fertilizer',
  'Fiddle Leaf Fig Plant Food',
  'Monstera Plant Food',
  'African Violet Fertilizer',
  'Alocasia Fertilizer',
  'Anthurium Fertilizer',
  'Bamboo Fertilizer',
  'Brazilian Wood Plant Food',
  'Carnivorous Plant Food',
  'Curry Leaf Plant Fertilizer',
  'Elephant Ear Fertilizer',
  'Hoya Fertilizer',
  'Lucky Bamboo Fertilizer',
  'Orchid Plant Food',
  'Peace Lily Fertilizer',
  'Pitcher Plant Food'
];

export const gardenPlantsList = [
  'Bougainvillea Fertilizer',
  'Camellia Fertilizer',
  'Cut Flower Food',
  'Desert Rose Fertilizer',
  'Flowering Fertilizer',
  'Rose Bush Fertilizer',
  'Rose Fertilizer',
  'Plumeria Fertilizer',
  'Hydrangea Fertilizer',
  'Hibiscus Fertilizer',
  'Azalea Fertilizer',
  'Gardenia Fertilizer',
  'Rhododendron Fertilizer',
  'Petunia Fertilizer',
  'Geranium Fertilizer',
  'Hanging Basket Plant Food',
  'Flowering Plant Food',
  'Daffodil Bulb Fertilizer',
  'Tulip Bulb Fertilizer',
  'Mum Fertilizer',
  'Ixora Fertilizer',
  'Bulb Fertilizer',
  'Lilac Bush Fertilizer',
  'Bloom Fertilizer',
  'Berry Fertilizer',
  'Pepper Fertilizer',
  'Tomato Fertilizer',
  'Strawberry Fertilizer',
  'Blueberry Fertilizer',
  'Herbs and Leafy Greens Plant Food',
  'Vegetable Fertilizer',
  'Pumpkin Fertilizer',
  'Potato Fertilizer',
  'Garlic Fertilizer',
  'Water Soluble Fertilizer',
  'Garden Fertilizer',
  'Plant Food Outdoor',
  'Plant Food',
  'Plant Fertilizer',
  'All Purpose Fertilizer',
  'All Purpose NPK Fertilizer',
  'Starter Fertilizer',
  '10-10-10 for General Use',
  '10-10-10 for Vegetables',
  '10-10-10 for Plants',
  'Fall Fertilizer',
  'Winter Fertilizer',
  'Ivy Plant Food',
  'Lawn Fertilizer',
  'Mycorrhizal Fungi for Trees',
  'Mycorrhizal Fungi for Palm Trees',
  'Mycorrhizal Fungi for Gardens',
  'Mycorrhizal Fungi for Citrus Trees',
  'Mycorrhizal Fungi',
  'Root Booster for Plants',
  'Soil Microbes for Gardening',
  'Trichoderma for Plants'
];

export const hydroAquaticList = [
  'Liquid Plant Food',
  'Lotus Fertilizer',
  'Aquarium Plant Fertilizer',
  'Aquatic Plant Fertilizer',
  'Water Garden Fertilizer',
  'Water Plant Fertilizer',
  'Hydroponic Nutrients',
  'Hydroponic Plant Food'
];

export const supplementsList = [
  'Fish Emulsion Fertilizer',
  'Fish Fertilizer',
  'Silica for Plants',
  'Cal-Mag Fertilizer',
  'Seaweed Fertilizer',
  'Calcium for Plants',
  'Calcium Nitrate',
  'Worm Castings Concentrate',
  'Compost Starter and Accelerator',
  'Compost Tea',
  'Sulfur for Plants',
  'Phosphorus Fertilizer',
  'Potassium Fertilizer',
  'Ferrous Sulfate For Plants',
  'Urea Fertilizer',
  'Magnesium for Plants',
  'Potassium Nitrate Fertilizer',
  'Ammonium Nitrate Fertilizer',
  'Potassium Sulfate Fertilizer',
  'Sulfate Of Potash',
  'Potash Fertilizer',
  'Muriate Of Potash',
  'Phosphorus and Potassium Fertilizer',
  'Compost Tea for Plants',
  'Kelp Meal Fertilizer',
  'Nitrogen Fertilizer',
  'Seaweed Extract for Plants',
  'pH Down',
  'pH Up'
]; 